site_name: RemotePro
site_description: PowerShell WPF GUI for MilestonePSTools
site_author: 'Cody Paternostro'
repo_url: https://github.com/codypaternostro/RemotePro.git

theme:
  name: material
  palette:
    scheme: white
    primary: white

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Configuration: getting-started/configuration.md
      - Usage Guide: getting-started/usage-guide.md
  - Commands:
      - Add-RpConfigCommand: en-US/Add-RpConfigCommand.md
      - Find-RpConfigCommand: en-US/Find-RpConfigCommand.md
      - Find-RpDefaultConfigCommands: en-US/Find-RpDefaultConfigCommands.md
      - Get-RpConfigCommands: en-US/Get-RpConfigCommands.md
      - Get-RpConfigPath: en-US/Get-RpConfigPath.md
      - Get-RpConnectionProfile: en-US/Get-RpConnectionProfile.md
      - Get-RpControllerObject: en-US/Get-RpControllerObject.md
      - Get-RpDefaultConfigCommandDetails: en-US/Get-RpDefaultConfigCommandDetails.md
      - Get-RpEventHandlers: en-US/Get-RpEventHandlers.md
      - Get-RPLogPath: en-US/Get-RPLogPath.md
      - Get-RpRunspaceEvents: en-US/Get-RpRunspaceEvents.md
      - Get-RpTicketBlock: en-US/Get-RpTicketBlock.md
      - Get-RpVmsHardwareCustom: en-US/Get-RpVmsHardwareCustom.md
      - Get-RpVmsItemStateCustom: en-US/Get-RpVmsItemStateCustom.md
      - Import-RpConfig: en-US/Import-RpConfig.md
      - Import-RpDefaultConfigCommandIds: en-US/Import-RpDefaultConfigCommandIds.md
      - Initialize-RpOpenRunspaces: en-US/Initialize-RpOpenRunspaces.md
      - Initialize-RpRunspaceJobs: en-US/Initialize-RpRunspaceJobs.md
      - Initialize-RpRunspaceResults: en-US/Initialize-RpRunspaceResults.md
      - Invoke-RpCommandObject: en-US/Invoke-RpCommandObject.md
      - New-RpAppDataPath: en-US/New-RpAppDataPath.md
      - New-RpConfigCommandJson: en-US/New-RpConfigCommandJson.md
      - New-RpControllerObject: en-US/New-RpControllerObject.md
      - Remove-RpConfigCommand: en-US/Remove-RpConfigCommand.md
      - Reset-RpConfigCommandDefaults: en-US/Reset-RpConfigCommandDefaults.md
      - Set-RpConfigCommands: en-US/Set-RpConfigCommands.md
      - Set-RpConfigDefaults: en-US/Set-RpConfigDefaults.md
      - Set-RPConnectionProfile: en-US/Set-RPConnectionProfile.md
      - Set-RpDefaultConfigCommandIds: en-US/Set-RpDefaultConfigCommandIds.md
      - Set-RpEventHandlers: en-US/Set-RpEventHandlers.md
      - Set-RpMutexLogAndUI: en-US/Set-RpMutexLogAndUI.md
      - Set-RpRunspaceEvents: en-US/Set-RpRunspaceEvents.md
      - Set-RpRunspaceEventsLegacyVersion: en-US/Set-RpRunspaceEventsLegacyVersion.md
      - Show-RpCamera: en-US/Show-RpCamera.md
      - Show-RpItemPicker: en-US/Show-RpItemPicker.md
      - Show-RPProfileEntryDialog: en-US/Show-RPProfileEntryDialog.md
      - Start-RpRemotePro: en-US/Start-RpRemotePro.md
      - Start-RpRunspaceJob: en-US/Start-RpRunspaceJob.md
      - Start-RpRunspaceJobStatic: en-US/Start-RpRunspaceJobStatic.md
      - Start-RpRunspaceMonitor: en-US/Start-RpRunspaceMonitor.md
      - Test-RequiresVmsConnection: en-US/Test-RequiresVmsConnection.md
      - Test-RpVmsConnection: en-US/Test-RpVmsConnection.md
      - Update-RpConfigCommand: en-US/Update-RpConfigCommand.md
      - Watch-RpRunspaces: en-US/Watch-RpRunspaces.md
  - Changelog: CHANGELOG/CHANGELOG.md

plugins:
  - search:
  - resize-images:
      source-dir: assets-large
      target-dir: assets
      enable_cache: True
      size: [800, 600]
      extensions: ['.jpg', '.jpeg', '.png', '.gif', '.svg']




































