site_name: RemotePro
site_description: PowerShell WPF GUI for MilestonePSTools
site_author: 'Cody Paternostro'
repo_url: https://github.com/codypaternostro/RemotePro
copyright: >
  Copyright &copy; 2024-2025 Cody Paternostro. All rights reserved.
  <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  palette:
    scheme: default
    primary: white
    accent: white
  icon:
    admonition:
    note: octicons/tag-16
  extra_css:
    - stylesheets/extra.css

  logo: assets/RpLogo.png
  features:
  - content.code.copy
  - content.code.annotate
  - navigation.instant
  - navigation.tabs
  - navigation.top
  - search.suggest
  - search.highlight
  - search.share

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Configuration: getting-started/configuration.md
      - Usage Guide: getting-started/usageguide.md
  - Commands:
      - Add-RpConfigCommand: en-US/Add-RpConfigCommand.md
      - Add-RpSettingToJson: en-US/Add-RpSettingToJson.md
      - Find-RpConfigCommand: en-US/Find-RpConfigCommand.md
      - Find-RpDefaultConfigCommands: en-US/Find-RpDefaultConfigCommands.md
      - Find-RpSettingsJson: en-US/Find-RpSettingsJson.md
      - Get-RpConfigCommands: en-US/Get-RpConfigCommands.md
      - Get-RpConfigPath: en-US/Get-RpConfigPath.md
      - Get-RpConnectionProfile: en-US/Get-RpConnectionProfile.md
      - Get-RpControllerObject: en-US/Get-RpControllerObject.md
      - Get-RpDefaultConfigCommandDetails: en-US/Get-RpDefaultConfigCommandDetails.md
      - Get-RpEventHandlers: en-US/Get-RpEventHandlers.md
      - Get-RpIconPath: en-US/Get-RpIconPath.md
      - Get-RpLogPath: en-US/Get-RpLogPath.md
      - Get-RpRunspaceEvents: en-US/Get-RpRunspaceEvents.md
      - Get-RpSettings: en-US/Get-RpSettings.md
      - Get-RpSettingsJsonPath: en-US/Get-RpSettingsJsonPath.md
      - Get-RpTicketBlock: en-US/Get-RpTicketBlock.md
      - Get-RpVmsHardwareCustom: en-US/Get-RpVmsHardwareCustom.md
      - Get-RpVmsItemStateCustom: en-US/Get-RpVmsItemStateCustom.md
      - Import-RpConfig: en-US/Import-RpConfig.md
      - Import-RpDefaultConfigCommandIds: en-US/Import-RpDefaultConfigCommandIds.md
      - Import-RpSettingsFromJson: en-US/Import-RpSettingsFromJson.md
      - Initialize-RpOpenRunspaces: en-US/Initialize-RpOpenRunspaces.md
      - Initialize-RpRunspaceJobs: en-US/Initialize-RpRunspaceJobs.md
      - Initialize-RpRunspaceResults: en-US/Initialize-RpRunspaceResults.md
      - Invoke-RpCommandObject: en-US/Invoke-RpCommandObject.md
      - New-RpAppDataPath: en-US/New-RpAppDataPath.md
      - New-RpConfigCommandJson: en-US/New-RpConfigCommandJson.md
      - New-RpControllerObject: en-US/New-RpControllerObject.md
      - New-RpSettingsJson: en-US/New-RpSettingsJson.md
      - Remove-RpConfigCommand: en-US/Remove-RpConfigCommand.md
      - Remove-RpSettingFromJson: en-US/Remove-RpSettingFromJson.md
      - Reset-RpConfigCommandDefaults: en-US/Reset-RpConfigCommandDefaults.md
      - Reset-RpSettingsJson: en-US/Reset-RpSettingsJson.md
      - Set-RpConfigCommands: en-US/Set-RpConfigCommands.md
      - Set-RpConfigDefaults: en-US/Set-RpConfigDefaults.md
      - Set-RpConnectionProfile: en-US/Set-RpConnectionProfile.md
      - Set-RpDefaultConfigCommandIds: en-US/Set-RpDefaultConfigCommandIds.md
      - Set-RpEventHandlers: en-US/Set-RpEventHandlers.md
      - Set-RpMutexLogAndUI: en-US/Set-RpMutexLogAndUI.md
      - Set-RpRunspaceEvents: en-US/Set-RpRunspaceEvents.md
      - Set-RpRunspaceEventsLegacyVersion: en-US/Set-RpRunspaceEventsLegacyVersion.md
      - Set-RpSettingsJson: en-US/Set-RpSettingsJson.md
      - Set-RpSettingsJsonDefaults: en-US/Set-RpSettingsJsonDefaults.md
      - Set-RpWindowIcon: en-US/Set-RpWindowIcon.md
      - Show-RpCamera: en-US/Show-RpCamera.md
      - Show-RpItemPicker: en-US/Show-RpItemPicker.md
      - Show-RpProfileEntryDialog: en-US/Show-RpProfileEntryDialog.md
      - Start-RpRemotePro: en-US/Start-RpRemotePro.md
      - Start-RpRunspaceJob: en-US/Start-RpRunspaceJob.md
      - Start-RpRunspaceJobStatic: en-US/Start-RpRunspaceJobStatic.md
      - Start-RpRunspaceMonitor: en-US/Start-RpRunspaceMonitor.md
      - Test-RpRequiresVmsConnection: en-US/Test-RpRequiresVmsConnection.md
      - Test-RpVmsConnection: en-US/Test-RpVmsConnection.md
      - Update-RpConfigCommand: en-US/Update-RpConfigCommand.md
      - Update-RpSettingsJson: en-US/Update-RpSettingsJson.md
      - Watch-RpRunspaces: en-US/Watch-RpRunspaces.md
  - Changelog: CHANGELOG/CHANGELOG.md

plugins:
  - glightbox
  - search
  - tags
  - resize-images:
      source-dir: assets-large
      target-dir: assets
      enable_cache: True
      size: [800, 600]
      extensions: ['.jpg', '.jpeg', '.png', '.gif', '.svg']

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences


extra:
  consent:
    actions:
    - accept
    - manage
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
















