name: Publish Module

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Install and cache PowerShell modules
      - name: Install and cache PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v6.2.1
        with:
          modules-to-cache: BuildHelpers

      # Check if the version has been bumped
      - name: Check if version has been bumped
        shell: powershell
        id: check_if_versions_bumped
        run: |
          [version]$GalleryVersion = Get-NextNugetPackageVersion -Name RemotePro -ErrorAction Stop
          [version]$GithubVersion = Get-MetaData -Path ./RemotePro/RemotePro.psd1 -PropertyName ModuleVersion -ErrorAction Stop
          $bumped = $GithubVersion -ge $GalleryVersion

          # Set environment variable instead of set-output
          echo "VERSION_BUMPED=$bumped" >> $env:GITHUB_ENV

      # Publish to PSGallery if version is bumped
      - name: Publish to PSGallery
        shell: pwsh
        if: env.VERSION_BUMPED == 'True'
        env:
          PSGALLERY_API_KEY: ${{ secrets.PS_GALLERY_KEY }}
        run: ./build.ps1 -Task Publish -Bootstrap
